version: "3.6"

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - /Users/parkergordon/GitRepos/k8-scripts/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
